In [1]:
import numpy as np
from scipy import linalg, sparse


# 1 check square matrix

In [2]:

m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
def isSquare (m): 
    return all (len (row) == len (m) for row in m)
isSquare(m)



False

In [ ]:
# Importing NumPy Library
import numpy as np
import sys



# This is my matrix

A = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(A)

dimension = A.shape
print(dimension)

# Reading number of rows
n = int(input('Enter number of rows: '))


# Reading number of columns
m = int(input('Enter number of columns: '))



        
# compare the number of rows and the number of columns to check square matrix
if(n == m):
    print("1")
else:
    print("0")
    



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


# problem 2

In [ ]:
# check the input matrix is square
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
def isSquare (m): return all (len (row) == len (m) for row in m)

In [ ]:
#compute the matrix rank
from numpy.linalg import matrix_rank
matrix_rank(np.eye(4)) 
a3 = np.array([[1,2],[2,4]])
matrix_rank(a3) 

In [ ]:
# compute matrix determinant
a2 = np.array([[1,2],[2,4]])
result2 =  np.linalg.det(a2)
print(result2)

In [ ]:
a2 = np.array([[1,2],[2,4]])
if (matrix_rank(a2) == len(a2)):
    print(1)
else:
    print(0)
        

# problem 4

In [ ]:
# Importing NumPy Library
import numpy as np
import sys

# Reading number of unknowns
n = int(input('Enter number of unknowns: '))

# Making numpy array of n x n+1 size and initializing 
# to zero for storing augmented matrix
a = np.zeros((n,n+1))

# Making numpy array of n size and initializing 
# to zero for storing solution vector
x = np.zeros(n)

# Reading augmented matrix coefficients
print('Enter Augmented Matrix Coefficients:')
for i in range(n):
    for j in range(n+1):
        a[i][j] = float(input( 'a['+str(i)+']['+ str(j)+']='))

# Applying Gauss Elimination
for i in range(n):
    if a[i][i] == 0.0:
        sys.exit('Divide by zero detected!')
        
    for j in range(i+1, n):
        ratio = a[j][i]/a[i][i]
        
        for k in range(n+1):
            a[j][k] = a[j][k] - ratio * a[i][k]

# Back Substitution
x[n-1] = a[n-1][n]/a[n-1][n-1]

for i in range(n-2,-1,-1):
    x[i] = a[i][n]
    
    for j in range(i+1,n):
        x[i] = x[i] - a[i][j]*x[j]
    
    x[i] = x[i]/a[i][i]

# Displaying solution
print('\nRequired solution is: ')
for i in range(n):
    print('X%d = %0.2f' %(i,x[i]), end = '\t')

In [ ]:
def number_row(i):
    "Count the number of rows in matrix A."
    n = A.shape[0]
    E = np.eye(n)
    if i == j:
        E[i,i] = k + 1
    else:
        E[i,j] = k
    return E @ A

def Is_square(m):
    arra = np.array(m)     
    for p in range(len(arra)):  
        for q in range(len(arra[p])):  
            if arra[p][q] == 0 and p < len(arra)-1: 
                arra[p+1][q] = 0  
            element_sum += arra[p][q]  
    return element_sum
m = [[1, 1, 0, 2],
          [0, 3, 0, 3], 
          [1, 0, 4, 4]]
print("Original matrix:")
print(m)
print("Sum:")
print(sum_matrix_Elements(m))

# problem 5
Solve linear system

In [ ]:
# Making numpy array of n x n+1 size and initializing 
# to zero for storing augmented matrix
a = np.zeros((n,n+1))

# Making numpy array of n size and initializing 
# to zero for storing solution vector
x = np.zeros(n)

# Reading augmented matrix coefficients
print('Enter Augmented Matrix Coefficients:')
for i in range(n):
    for j in range(n+1):
        a[i][j] = float(input( 'a['+str(i)+']['+ str(j)+']='))

In [ ]:
A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
B = np.array([25, -10, -4])
X2 = np.linalg.solve(A,B)

print(X2)